/* tslint:disable */
/* eslint-disable */
/**
 * Finder
 * A web app for finding PDCM gene expression data for end-users based on data-set.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GeneExpression,
} from '../models';
import {
    GeneExpressionFromJSON,
    GeneExpressionToJSON,
} from '../models';

/**
 * 
 */
export class GenesApi extends runtime.BaseAPI {

    /**
     * Retrieves the expression gene data for end-users
     * Retrieves the expression gene data for end-users
     */
    async getExpressionDataRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GeneExpression>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/genes`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GeneExpressionFromJSON));
    }

    /**
     * Retrieves the expression gene data for end-users
     * Retrieves the expression gene data for end-users
     */
    async getExpressionData(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GeneExpression>> {
        const response = await this.getExpressionDataRaw(initOverrides);
        return await response.value();
    }

}
